### ISSUE TITLE
Sökfunktion

### ISSUE THREAD

**Issue by fjohansson92** [WheresMarco/1DV450-mh222zr-API#12]
Fungerar inte. Places har inget attribut som heter 'title'. Sen kom jag inte åt metoden utan att ändra i routes.

**Comment by WheresMarco** [comment]
En miss när jag förde över koden från mitt andra repo till det här (lång historia...). Kommer fixas.

**Comment by WheresMarco** [comment]
Jag hade missat att inkludera sök-anropet i postman-filen. Lade till som den skulle fungera och testade den med lyckat resultat :smile:
