### ISSUE TITLE
Felmeddelanden

### ISSUE THREAD

**Issue by fjohansson92** [WheresMarco/1DV450-mh222zr-API#16]
Finns några fel som inte tas hand om, tex om man försöker skapa en händelse utan tagg. Felmeddelandena är oftast bra men de skulle gärna få vara lite mer specifika, 'Please check you parameters' säger inte så mycket.

**Comment by WheresMarco** [comment]
Kommer nog pumpa in det riktiga felmeddelandet som svar istället.
