### ISSUE TITLE
Sammanfattning

### ISSUE THREAD

**Issue by fjohansson92** [WheresMarco/1DV450-mh222zr-API#17]
Postman filen innehöll inte alla anropp som behövdes men det var bra att de flesta fanns med.
Finns lite buggar att fixa sen är det viktigt att du gör om de värsta delarna som bryter mot RESTful tänket och HATEOAS. Utöver det tycker jag du uppfyller minimum kraven för uppgiften. Geocoder gemet tycker jag var intressant använde dock SQLLite så provade inte det. 
Lycka till!

**Comment by WheresMarco** [comment]
Tack för feedbacken :smile: 

Mycket av felen du har hittat beror på tidsbrist. Det kommer att fixas i slutet på veckan.

Geocoder är ganska nice... om man använder en annan DB än SQLLite (https://github.com/alexreisner/geocoder#distance-queries-in-sqlite). 

Dock kommer det att lösa sig när jag publicerar appen på t.ex. Heroku.
