### ISSUE TITLE
Jh222vp utvärdering Registreringsapplikation

### ISSUE THREAD

**Issue by jh222vp** [WheresMarco/1DV450-mh222zr-API#4]
Hej,

Nu fick jag igång applikationen och den verkar fungerar som den ska och följer kraven. :+1: 

Lite saker jag upptäckte var följande:

Modifierar man adressfältet och ändrar sökvägarna så hamnar man på en "röd-ful" felsida som talar om för mig att det inte gick att routa mitt anrop till något som matchar det jag sökte efter. Detta kanske kunde lösas genom att man routar om "ful-sidorna" till en egengjord sådan som också kanske kan innehålla en tillbaka-knapp.

Jag tyckte också att det var lite märkligt att Admin blir tilldelad en API-nyckel samt att hela kontot tas bort för att skrota en API-nyckel på både användare samt admin. Ett förslag är att man sätter nyckelfältet i tabellen på användaren till nil för att endast ta bort API-nyckeln och inte hela användaren.

När man inloggad på admin kontot så syns också API nyckeln för admin två gånger. En gång uppe vid "Your API-key" samt en gång till under "All users". Lite överflödigt kan tyckas.
http://s24.postimg.org/o6zm5ztd1/Capture.png

Sammanfattning
Jag tycker att du gjort en schysst sida och den gör jobbet bra. Det jag har påpekat ovan kan du säkerligen lätt fixa till då de är småsaker och jag tycker din applikation är godkänd! Bra jobbat! :)

//Jonas

**Comment by WheresMarco** [comment]
Tack för feedbacken :+1: 

Kommer fixa ful-sidorna när tillfället ges.

Eftersom man bara får tillgång till en nyckel tog jag beslutet att binda ihop det med kontot så pass hårt som det är. Jag kände att det var bra att dela upp det i olika controllers så att nycklarna genereras i en controller, och om man vill lägga till funktionalitet för nycklar kan man göra det på ett ställe.

Jag kommer nog dölja admin's nyckel och bara tillåta admin att ta bort andras konto. Även lägga till funktionen för att göra andra användare admin.

**Comment by 1dv450** [comment]
:+1:
